### ISSUE TITLE
Route to new address?

### ISSUE THREAD

**Issue by FryDay** [marwan-at-work/vecty-router#2]
Is there currently a way to redirect to a new address? For example, I have a user login and want to redirect them back to "/"...I can't figure out how to get that to work. If it's not currently possible, are you open to pull requests?

**Comment by marwan-at-work** [comment]
@FryDay totally open to pull requests :) The package needs to let the user programmatically navigate to a route instead of just declaratively. You can, therefore, just expose the internals of this method here in a sensical way https://github.com/marwan-at-work/vecty-router/blob/master/link.go#L33 
let me know if this solves your issue.

**Comment by FryDay** [comment]
That's what I figured, but wanted to make sure I wasn't missing anything. Awesome, I plan to work on that and I'll open a PR when I'm satisfied with it.
